services:
  - type: web
    name: velozity-backend
    env: node
    branch: main
    plan: free
    buildCommand: npm ci
    startCommand: node server.js
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20.17.0
      - key: ALLOWED_ORIGINS
        value: https://vasdash.netlify.app,https://web-sandbox.oaiusercontent.com
      - key: DB_PATH
        value: /var/data/data.sqlite
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1
